name: rm_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ferry: ^0.10.4
  gql_http_link: ^0.4.0
  ferry_flutter: ^0.5.4
  get_it: ^7.2.0
  flutter_slidable: ^1.3.0
  uuid: ^3.0.6
  rm_graphql_client:
    path: ../rm_graphql_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  ferry_generator: ^0.4.4
  build_runner: ^2.1.11

flutter:

  uses-material-design: true
